//
// Generated by GraphQLGenerator
// DO NOT MODIFY!
//

import Foundation

public struct HumanFragment: Decodable, Equatable {

    public let name: String
    public let appearsIn: Optional<Episode>

    public enum CodingKeys: String, CodingKey {
        case name
        case appearsIn
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        name = try values.decode(String.self, forKey: CodingKeys.name)
        appearsIn = try values.decode(Optional<Episode>.self, forKey: CodingKeys.appearsIn)
    }
}

public struct CreateReview: Codable, Equatable {

    public let stars: Int

    public struct Data: Decodable, Equatable {

        public let createReview: Optional<Review>

        public struct Review: Decodable, Equatable {

            public let stars: Int

            public enum CodingKeys: String, CodingKey {
                case stars
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: CodingKeys.self)
                stars = try values.decode(Int.self, forKey: CodingKeys.stars)
            }
        }
    }
}

public struct Search: Codable, Equatable {

    public struct Data: Decodable, Equatable {

        public let search: Optional<SearchResult>

        public enum SearchResult: Decodable, Equatable {

            case human(human: Human)
            case droid(droid: Droid)
            case starship(starship: Starship)

            enum ItemTypeKey: String, CodingKey {
                case typeName = "__typename"
            }

            public init(from decoder: Decoder) throws {
                let typeValues = try decoder.container(keyedBy: ItemTypeKey.self)
                let type = try typeValues.decode(String.self, forKey: .typeName)
                switch type {
                case "Human":
                    self = .human(human: try Human(from: decoder))
                case "Droid":
                    self = .droid(droid: try Droid(from: decoder))
                case "Starship":
                    self = .starship(starship: try Starship(from: decoder))
                default:
                    throw DecodingError.dataCorruptedError(
                        forKey: ItemTypeKey.typeName,
                        in: typeValues,
                        debugDescription: "Type \(type) is not a valid type for \(SearchResult.self)"
                    )
                }
            }
        }

        public struct Human: Decodable, Equatable {

            public let humanFragment: HumanFragment

            public enum CodingKeys: String, CodingKey {
                case humanFragment
            }

            public init(from decoder: Decoder) throws { humanFragment = try HumanFragment(from: decoder) }
        }

        public struct Droid: Decodable, Equatable {

            public let name: String

            public enum CodingKeys: String, CodingKey {
                case name
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: CodingKeys.self)
                name = try values.decode(String.self, forKey: CodingKeys.name)
            }
        }

        public struct Starship: Decodable, Equatable {

            public let name: String

            public enum CodingKeys: String, CodingKey {
                case name
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: CodingKeys.self)
                name = try values.decode(String.self, forKey: CodingKeys.name)
            }
        }
    }
}

public enum Episode: String, Decodable, Equatable {
    case NEWHOPE
    case EMPIRE
    case JEDI
}
